"use client";

import { LazyMotion, domAnimation, m } from "framer-motion";
import { CheckCircle2 } from "lucide-react";

export default function RequestLifecycle() {
  const lifecycle = [
    {
      title: "User Initialization",
      description: "Developer runs a command like `ob \"update the header\" @components/header.tsx`.",
    },
    {
      title: "Context Bundling",
      description: "CLI resolves the `@` references, reads local files, and packages them into a compressed context payload.",
    },
    {
      title: "Bridge Routing",
      description: "The payload is sent to the local Fastify bridge (port 5000), which emits an event to the extension.",
    },
    {
      title: "DOM Injection",
      description: "The extension receives the event, populates the AI provider's text area, and simulates a submit click.",
    },
    {
      title: "Real-time Scraping",
      description: "A MutationObserver watches the DOM for new tokens generated by the AI and streams them back to the Bridge.",
    },
    {
      title: "Parsing & Execution",
      description: "The parser extracts JSON operations, validates them, and applies the changes to the user's workspace.",
    },
  ];

  return (
    <section className="py-24 bg-[#0a0a0a] border-t border-border">
      <div className="container mx-auto px-4 max-w-4xl">
        <div className="text-center mb-16 space-y-4">
          <h2 className="text-3xl sm:text-4xl font-bold text-foreground">Request Lifecycle</h2>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            The chronological journey of a single prompt from the terminal, through the browser, and back to the filesystem.
          </p>
        </div>

        <LazyMotion features={domAnimation}>
          <div className="relative pl-8 sm:pl-0">
            {/* Timeline Line */}
            <div className="absolute left-8 sm:left-1/2 top-0 bottom-0 w-px bg-border sm:-translate-x-1/2" />

            <div className="space-y-12">
              {lifecycle.map((step, idx) => (
                <m.div
                  key={idx}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, margin: "-100px" }}
                  transition={{ duration: 0.5 }}
                  className={`relative flex flex-col sm:flex-row items-start sm:items-center gap-8 ${
                    idx % 2 === 0 ? "sm:flex-row-reverse" : ""
                  }`}
                >
                  <div className="hidden sm:block flex-1" />
                  
                  {/* Timeline Dot */}
                  <div className="absolute left-[-9px] sm:left-1/2 sm:-translate-x-1/2 w-5 h-5 rounded-full bg-background border-4 border-[#EE8B50] z-10 flex items-center justify-center">
                    <div className="w-1.5 h-1.5 rounded-full bg-[#EE8B50]" />
                  </div>

                  <div className={`flex-1 ${idx % 2 === 0 ? "sm:text-right" : "sm:text-left"} pl-8 sm:pl-0`}>
                    <div className="p-6 rounded-2xl bg-card border border-border hover:border-[#EE8B50]/30 transition-colors shadow-sm">
                      <div className={`flex items-center gap-2 mb-2 ${idx % 2 === 0 ? "sm:justify-end" : "sm:justify-start"}`}>
                        <CheckCircle2 className="w-4 h-4 text-[#EE8B50]" />
                        <h3 className="font-bold text-foreground">{step.title}</h3>
                      </div>
                      <p className="text-sm text-muted-foreground leading-relaxed">
                        {step.description}
                      </p>
                    </div>
                  </div>
                </m.div>
              ))}
            </div>
          </div>
        </LazyMotion>
      </div>
    </section>
  );
}
