"use client";

import { LazyMotion, domAnimation, m } from "framer-motion";
import { Chrome, Server, Terminal, Waves } from "lucide-react";

export default function StreamingPipeline() {
  return (
    <section className="py-20 bg-[#0a0a0a] border-t border-border overflow-hidden">
      <div className="container mx-auto px-4 max-w-5xl">
        <div className="text-center mb-16 space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#38BDF8]/10 text-[#38BDF8] border border-[#38BDF8]/20 text-xs font-semibold uppercase tracking-wider">
            <Waves className="w-3.5 h-3.5" />
            <span>Real-time Data Flow</span>
          </div>
          <h2 className="text-3xl sm:text-4xl font-bold text-foreground">Streaming Pipeline</h2>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            OpenBrowser does not wait for complete responses. Content is parsed and streamed via SSE directly from the browser to the terminal as it is generated by the AI provider.
          </p>
        </div>

        <LazyMotion features={domAnimation}>
          <div className="relative p-8 sm:p-12 rounded-3xl bg-card border border-border flex flex-col md:flex-row items-center justify-between gap-8 max-w-4xl mx-auto">
            {/* AI Provider */}
            <div className="flex flex-col items-center gap-3 z-10 w-full md:w-auto">
              <div className="w-16 h-16 rounded-2xl bg-emerald-400/10 border border-emerald-400/30 flex items-center justify-center text-emerald-400 shadow-[0_0_20px_rgba(52,211,153,0.15)]">
                <Chrome className="w-8 h-8" />
              </div>
              <span className="font-semibold text-sm">Browser Extension</span>
            </div>

            {/* Streaming Particles */}
            <div className="hidden md:flex flex-1 items-center justify-center h-24 relative overflow-hidden w-full">
              <div className="absolute inset-0 bg-[linear-gradient(to_right,transparent,rgba(56,189,248,0.1),transparent)]" />
              {[...Array(5)].map((_, i) => (
                <m.div
                  key={i}
                  initial={{ x: -100, opacity: 0 }}
                  animate={{ x: 300, opacity: [0, 1, 0] }}
                  transition={{
                    duration: 2,
                    repeat: Infinity,
                    delay: i * 0.4,
                    ease: "linear",
                  }}
                  className="absolute w-2 h-2 rounded-full bg-[#38BDF8] shadow-[0_0_10px_#38BDF8]"
                />
              ))}
            </div>
            
            {/* Mobile Streaming Particles */}
            <div className="md:hidden flex flex-col flex-1 items-center justify-center w-24 relative overflow-hidden h-32">
              {[...Array(3)].map((_, i) => (
                <m.div
                  key={i}
                  initial={{ y: -50, opacity: 0 }}
                  animate={{ y: 50, opacity: [0, 1, 0] }}
                  transition={{
                    duration: 1.5,
                    repeat: Infinity,
                    delay: i * 0.5,
                    ease: "linear",
                  }}
                  className="absolute w-2 h-2 rounded-full bg-[#38BDF8] shadow-[0_0_10px_#38BDF8]"
                />
              ))}
            </div>

            {/* Bridge */}
            <div className="flex flex-col items-center gap-3 z-10 w-full md:w-auto">
              <div className="w-16 h-16 rounded-2xl bg-[#38BDF8]/10 border border-[#38BDF8]/30 flex items-center justify-center text-[#38BDF8] shadow-[0_0_20px_rgba(56,189,248,0.15)]">
                <Server className="w-8 h-8" />
              </div>
              <span className="font-semibold text-sm">Bridge Server</span>
            </div>

            {/* Streaming Particles */}
            <div className="hidden md:flex flex-1 items-center justify-center h-24 relative overflow-hidden w-full">
              <div className="absolute inset-0 bg-[linear-gradient(to_right,transparent,rgba(238,139,80,0.1),transparent)]" />
              {[...Array(5)].map((_, i) => (
                <m.div
                  key={`cli-${i}`}
                  initial={{ x: -100, opacity: 0 }}
                  animate={{ x: 300, opacity: [0, 1, 0] }}
                  transition={{
                    duration: 2,
                    repeat: Infinity,
                    delay: i * 0.4 + 0.2,
                    ease: "linear",
                  }}
                  className="absolute w-2 h-2 rounded-full bg-[#EE8B50] shadow-[0_0_10px_#EE8B50]"
                />
              ))}
            </div>

            {/* Mobile Streaming Particles */}
            <div className="md:hidden flex flex-col flex-1 items-center justify-center w-24 relative overflow-hidden h-32">
              {[...Array(3)].map((_, i) => (
                <m.div
                  key={`cli-mobile-${i}`}
                  initial={{ y: -50, opacity: 0 }}
                  animate={{ y: 50, opacity: [0, 1, 0] }}
                  transition={{
                    duration: 1.5,
                    repeat: Infinity,
                    delay: i * 0.5 + 0.2,
                    ease: "linear",
                  }}
                  className="absolute w-2 h-2 rounded-full bg-[#EE8B50] shadow-[0_0_10px_#EE8B50]"
                />
              ))}
            </div>

            {/* CLI */}
            <div className="flex flex-col items-center gap-3 z-10 w-full md:w-auto">
              <div className="w-16 h-16 rounded-2xl bg-[#EE8B50]/10 border border-[#EE8B50]/30 flex items-center justify-center text-[#EE8B50] shadow-[0_0_20px_rgba(238,139,80,0.15)]">
                <Terminal className="w-8 h-8" />
              </div>
              <span className="font-semibold text-sm">CLI & Parser</span>
            </div>
          </div>
        </LazyMotion>
      </div>
    </section>
  );
}
